### ISSUE TITLE
How to separate p5 from non-p5 examples?

### ISSUE THREAD

**Issue by dariusk** [ml5js/ml5-examples#1]
Should we create a directory structure like this?

```
examples-p5/
examples-js/
```

I'm actually at a loss for what to call the "plain JavaScript" examples. Plain? Vanilla? ES2017? JavaScript? The problem of course being that p5 is *also* JavaScript.

**Comment by shiffman** [comment]
Dare we say:

```
examples/
examples-p5/
```

Another option is rather than have two versions of `examples` just have some depend on p5 and some not and be clear about that in documentation.

Some other ideas:

```
examples-js/
examples-p5-which-is-also-js-it-is-a-js-library/
```

```
examples-sans-p5
examples-p5
```

**Comment by cvalenzuela** [comment]
Since the repo is already called ml5-examples, what about having something like this:

```
javascript/
p5js/
```

And then we could have ML5 examples with other frameworks too:

```
javascript/
p5/
three/
rita/
pixi/
etc..
```
maybe its too much?

**Comment by handav** [comment]
Going through this for the first time, I think having the folder be called p5js is confusing. I like Darius and Dan's idea of having 'examples' in the folder names as well.

I don't think it's a bad idea to separate out the examples by framework/language, though.

**Comment by cvalenzuela** [comment]
Closing this because it seems resolved. We decided to go with this for now:
```
javascript/
p5/
three/
rita/
pixi/
etc..
```

**Comment by shiffman** [comment]
Love it! Looking forward to three.js examples! Say hi to @mrdoob at Eyeo this week! (Was such an honor to meet IRL!)

**Comment by mrdoob** [comment]
@shiffman same! 😊
