### ISSUE TITLE
(question) reading in many images, iterating through directories

### ISSUE THREAD

**Issue by handav** [ml5js/ml5-examples#10]
I'm working on an image classification example (like this one https://ml5js.github.io/docs/simple-image-classification-example.html) that uses a lot of images, and ideally saves the classifications to a json file.

What's the best way to read in a directory of images in p5, and iterate through them to get the image names? Is this something better suited for a regular js example, with a node server or something?

**Comment by handav** [comment]
(Also @shiffman I'm still not able to add labels to issues I create - can you give me the permissions for that?)

**Comment by shiffman** [comment]
This is a great idea. It'll be a little awkward to do this client-side so yes it may make sense to eventually create ml5 node or electron app examples for tasks like this.

To start though you could make a p5 example that does the following:

1. Load images
   * hardcoded array of filenames
   * "choose files" [see `createFileInput`](https://p5js.org/reference/#/p5/createFileInput) or ["drag/drop" example](https://p5js.org/examples/dom-drop.html) to upload a directory of images
2. Run all the images through classification model.
3. Save results using `saveJSON()` which will trigger an automatic download to browser default directory.

I'd be happy to help with this!

(looking into the label permissions thing)

**Comment by cvalenzuela** [comment]
Seems resolved!
