### ISSUE TITLE
v0.2.3 release - updating examples

### ISSUE THREAD

**Issue by joeyklee** [ml5js/ml5-examples#111]
Hello wonderful ml5 contributors,

### `ml5-examples/javascript`
- [X] No issues with image classification using MobileNet
- [ ] Issue with image classification using feature extractor
- [X] No issues with webcam classification using MobileNet.
- [X] No issues with PoseNet
- [X] No issues with StyleTransfer

### `ml5-examples/p5js`

- [X] CharRNN
- [X] FeatureExtractor
- [X] ImageClassification
- [X] KNNClassification
- [X] LSTM
- [x] PitchDetection
- [ ] Pix2Pix
- [x] PoseNet
- [x] SketchRNN
- [ ] StyleTransfer
- [x] Word2Vec
- [ ] YOLO

We recently released ml5.js v0.2.3 - https://github.com/ml5js/ml5-library/tree/release - and we're in the process of getting all of our examples and website synchronized. We could some help going through to make sure that:

1. all of the examples are working with the latest ml5.js version
2. the links and documentation to the website reflect all of the latest changes.

## Here's how you can help:

1. Go through the examples in this [ml5-examples](https://github.com/ml5js/ml5-examples) repo and test out each of the examples contained in: `/p5js` and `/javascript`
2. Make sure to run a local server on your computer so that any static assets are served while you're running and testing each example.
3. If there's an error: 
   i. make an issue in our github issues - https://github.com/ml5js/ml5-examples/issues 
   ii. If you plan to work on fixing those issues, please let us know you will be making those changes in your comment in the issue you just submitted.
   iii.  If you fix the error: please make sure that your pull request is going to the `release` branch

## Note:

If you're testing the ml5-examples, you may have to change the `index.html` file reference to the ml5 library. In this case, please be sure to use:

```html
<script src="https://unpkg.com/ml5@0.2.3/dist/ml5.min.js" type="text/javascript"></script>
```

Thank you! 🙏

**Comment by brondle** [comment]
Going through a few of these and thought I'd comment with my results so there's no redundant work going on. All examples were tested on an Apache local server in Chrome on a Mac.

**Javascript**
-No issues with image classification using MobileNet
- [Issue with image classification using feature extractor](https://github.com/ml5js/ml5-examples/issues/112  )
- No issues with webcam classification using MobileNet.
- No issues with PoseNet
- No issues with StyleTransfer

**Comment by brondle** [comment]
**p5js**

**FeatureExtractor** -- ALL CLEAR
- No issues with image classification using feature extractor
- No issues with image regression using feature extractor
**ImageClassification**
- No issues with MobileNet and p5.js
- No issues with multiple images
- No issues with webcam image classification
- No issues with image scavenger hunt
- No issues with VideoSound
- Didn't set up a google API key for translation yet, someone might want to check that out
**KNN Classification** -- ALL CLEAR
- No issues with PoseNet
- No issues with webcam
- No issues with VideoSound
- No issues with VideoSquare
**LSTM/CharRNN**
- [put in PR to change naming to reflect current conventions](https://github.com/ml5js/ml5-examples/pull/113)
- no issues with interactive text generation
- no issues with standard text generation
- no issues with stateful text generation

Taking a break now.

**Comment by joeyklee** [comment]
@brondle - you're awesome! Thank you so much for all the checks! Bravo!

**Comment by joeyklee** [comment]
**pix2pix**
- [X] p5js/Pix2Pix/Pix2Pix_callback/
- [ ] Pix2Pix/Pix2Pix_promise/ ==> err: `TypeError: ml5.pix2pix(...).then is not a function[Learn More]`

**Comment by myhendry** [comment]
I have done some examples integrating ml5 with reactjs (reference my github link below). I can contribute those if it is useful

https://github.com/myhendry/lab/tree/master/web-js/src/modules/ml5

**Comment by joeyklee** [comment]
Closing this for now as our focus will is now on https://github.com/ml5js/ml5-examples/issues/128 

Thanks for the help ya'll!
