### ISSUE TITLE
How to train images for style transfer ?

### ISSUE THREAD

**Issue by b2renger** [ml5js/ml5-examples#15]
In this page : https://ml5js.github.io/docs/style-transfer-image-example.html#

It is mentioned that you can train your own images but the link refers to the very same page. Is it an error or the tutorial is just not available yet ?

**Comment by cvalenzuela** [comment]
Hi @b2renger, this is still a WIP. @yining1023 is working on this. we will have updates soon!

**Comment by b2renger** [comment]
Great thanks !
