### ISSUE TITLE
Missing javascript file in the sentiment example

### ISSUE THREAD

**Issue by pujaarajan** [ml5js/ml5-examples#174]
The "Sentiment" example is missing the javascript file. See [here](https://github.com/ml5js/ml5-examples/tree/release/javascript/Sentiment).

**Comment by joeyklee** [comment]
@pujaarajan - oops! Thanks for noticing this. I will fix this asap! 🙏

**Comment by joeyklee** [comment]
@pujaarajan - Quick note: I realized that the example in javascript/sentiment is currently a placeholder and still needs to be ported to plain javascript from p5.js which is part of a larger effort herer: https://github.com/ml5js/ml5-examples/pull/165.

**Comment by joeyklee** [comment]
@pujaarajan - This should be resolved now with the latest release of examples. Thanks!

@all-contributors please add @pujaarajan for bug

**Comment by pujaarajan** [comment]
@joeyklee Happy to help test anything in the future!
