### ISSUE TITLE
Problem in running in local host

### ISSUE THREAD

**Issue by MohamedAfham** [ml5js/ml5-examples#185]
## → Description 📝

- found a bug 🐛
I downloaded the exact image data as given in the repository and I tried the exact .html and .js files as well but I couldn't be able to get the appropriate result in my local host. 

## → Screenshots 🖼
![Screenshot (165)](https://user-images.githubusercontent.com/46145275/64071988-28a33c00-cca4-11e9-83ae-0f5ecb18feb3.png)

## → Helpful Information 🦄

- **Web browser and version**  Chrome version 76.0
- **Operating System**  Windows

**Comment by joeyklee** [comment]
Hi @MohamedAfham - If you're running your localhost, in your browser window you should go to the url: `localhost:8080` or `localhost:8081` depending on which port your localhost is running on. 

See: https://ml5js.org/getting-started/running-examples/

**Comment by MohamedAfham** [comment]
Thank You! @joeyklee . I'll look onto that.

**Comment by joeyklee** [comment]
@MohamedAfham - I will close this now assuming you've managed to resolve this. Feel free to ping us with more questions if you're still having issues with this. Thanks!
