### ISSUE TITLE
Web Editor Examples - PoseNet, UNet, BodyPix

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-examples#186]
## → Description 📝

This is a continuation of #6 but opening a separate issue as it relates specifically to prepping material for the IMA course in https://github.com/ml5js/Intro-ML-Arts-IMA/pull/34.

For week 3 material, I'm providing examples for PoseNet, UNet, and BodyPix. 

* [ ] [PoseNet single image](https://editor.p5js.org/ml5/sketches/MmUoz2_thEa) is currently broken (see screenshot below)
* [ ] [UNet examples](https://github.com/ml5js/ml5-examples/tree/release/p5js/UNET/UNET_webcam) not included with upload to web editor script.
* [ ] [BodyPix examples](https://github.com/ml5js/ml5-examples/tree/release/p5js/BodyPix) not included with upload to web editor script.

@joeyklee I can create web editor versions of UNet and BodyPix and put them in the `ima_ml` if that's more expedient. Also are they perhaps not included b/c there is an issue with the model and the p5 web editor? I'll do some tests and report back here!
 
## → Screenshots 🖼

<img width="1644" alt="Screen Shot 2019-09-15 at 9 56 30 AM" src="https://user-images.githubusercontent.com/191758/64922638-6ec9c680-d79f-11e9-8085-f956da88c268.png">

☝️This is the same error we ran into with image classification but since that example now works in theory we can maybe get this one to! (I might also suggest switching it to `loadImage()` and use `preload()` but that's a different discussion 🤪)

**Comment by shiffman** [comment]
Noting a different error if I switch to `loadImage()` and `preload()`.

https://editor.p5js.org/ima_ml/sketches/sk1ZWdEBu

<img width="1385" alt="Screen Shot 2019-09-15 at 10 09 43 AM" src="https://user-images.githubusercontent.com/191758/64922765-f532d800-d7a0-11e9-8a4a-fae087376356.png">

**Comment by shiffman** [comment]
UNet works!

https://editor.p5js.org/ima_ml/sketches/ii30sqpgL

<img width="1410" alt="Screen Shot 2019-09-15 at 10 11 35 AM" src="https://user-images.githubusercontent.com/191758/64922795-3a570a00-d7a1-11e9-8cee-ec8f0ec137e8.png">

**Comment by shiffman** [comment]
BodyPix too!

https://editor.p5js.org/ima_ml/sketches/-R3ybO0uz

<img width="1452" alt="Screen Shot 2019-09-15 at 10 13 32 AM" src="https://user-images.githubusercontent.com/191758/64922832-97eb5680-d7a1-11e9-9625-6659f4b784b3.png">

**Comment by joeyklee** [comment]
@shiffman - I think this is resolved now, or? Feel free to reopen if this issue persists.
