### ISSUE TITLE
Create Teachable Machine sound classification example

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-examples#197]
## → Description 📝

We should make one like @joeyklee's #196. Maybe "clapping" vs. "background noise"? Here is my example code from class in case helpful.

https://editor.p5js.org/ima_ml/sketches/xcdqphiVj

**Comment by joeyklee** [comment]
Closing this with: https://github.com/ml5js/ml5-examples/tree/release/p5js/TeachableMachine/SoundModel_TM
