### ISSUE TITLE
Browser memory usage - PitchDetection

### ISSUE THREAD

**Issue by simog-dev** [ml5js/ml5-examples#228]
Hi, i'm finding a big memory usage of the browser using the PitchDetection model. After starting pitch detection the memory usage go up slowly and it continue until i close the browser tab or the browser crashes.

- **Web browser & version**: Firefox & Chrome
- **Operating System**: Windows 10
- **ml5 version you're using**: 0.4.1

**Comment by joeyklee** [comment]
@simog-dev - Oh! Thank you for reporting this. We'll have a look! 

 @shiffman  @yining1023 - if you have a moment to look at if there might be a memory leak that would be awesome.

**Comment by simog-dev** [comment]
Be updated on possible fix would be great! Thanks to you for this awsome repo.

**Comment by joeyklee** [comment]
@simog-dev - just a note that this will be resolved with https://github.com/ml5js/ml5-library/pull/688 in the next release `v0.4.3`

**Comment by joeyklee** [comment]
@simog-dev - this should now be resolved in v0.4.3. Closing now. Thank you!
