### ISSUE TITLE
Unexpected token F in JSON at position 0 on Word2Vec p5 Example

### ISSUE THREAD

**Issue by lisajamhoury** [ml5js/ml5-examples#245]
Dear ml5 community, 

I'm submitting a new issue. Please see the details below.

### → Step 1: Describe the issue 📝
> Did you find a bug? Want to suggest an idea for a new example?

In the Word2Vec example in both the p5 online editor and when run locally with http server all buttons respond with the same error 

Uncaught (in promise) SyntaxError: Unexpected token F in JSON at position 0

### → Step 2: Screenshots or Relevant Documentation 🖼
> Here's some helpful screenshots and/or documentation of the new feature 
<img width="210" alt="Screen Shot 2019-11-18 at 2 14 02 PM" src="https://user-images.githubusercontent.com/7552772/69082254-b8d46000-0a0d-11ea-9230-5179fc367c71.png">

### → Step 3: Share an example of the issue 🦄
> Here's some example code or a demonstration of the issue in https://github.com/ml5js/ml5-examples OR in the https://editor.p5js.org or codepen/jsfiddle/etc...

Issue happens in code as written in example on pressing any of the buttons.

**Other relevant information, if applicable**

### → Describe your setup 🦄
> Here's some helpful information about my setup...

- **Web browser & version**:Chrome Version 78.0.3904.97 (Official Build) (64-bit)
- **Operating System**: MacBook Air (Retina, 13-inch, 2018)
- **ml5 version you're using**: https://unpkg.com/ml5@0.4.3/dist/ml5.min.js
- **Any additional notes**

Thanks for all your great work on this!

**Comment by joeyklee** [comment]
Hi @lisajamhoury - Oh! Thanks for flagging this. I'll take a look and see what's going on here. Stay tuned.

**Comment by joeyklee** [comment]
Hmm ok so looks like the JSDelivr doesn't want to send anything larger than 20mb

https://cdn.jsdelivr.net/gh/ml5js/ml5-examples@release/p5js/Word2Vec/Word2Vec_Interactive/data/wordvecs10000.json 

![Screen Shot 2019-11-18 at 16 32 00](https://user-images.githubusercontent.com/3622055/69095764-073f2a00-0a21-11ea-936b-42d6e011f8aa.png)

I'll see what else we can do here.

**Comment by joeyklee** [comment]
Quick note is that if we link directly to the raw.github URL for the `json` file it works:

```js
 word2Vec = ml5.word2vec('https://raw.githubusercontent.com/ml5js/ml5-examples/release/p5js/Word2Vec/Word2Vec_Interactive/data/wordvecs10000.json', modelLoaded);
```

**Comment by joeyklee** [comment]
I'm going to flag this as a and `jsdelivr` issue. As  quick fix I will change the default model to the `5000` word vector. 

cc/ @catarak.

**Comment by joeyklee** [comment]
This is now resolved here: https://editor.p5js.org/ml5/sketches/Word2Vec_Interactive 

Thanks @lisajamhoury

**Comment by lisajamhoury** [comment]
Awesome! Thanks!
