### ISSUE TITLE
PoseNet example with Single detection gives Uncaught (in promise) Error

### ISSUE THREAD

**Issue by CreativeCode** [ml5js/ml5-examples#25]
Great initiative with ML5. When trying to run the "PoseNet example with Single detection" on Chrome Version 66.0.3359.181 (Official Build) (64-bit) I get the following error:
```
Uncaught (in promise) Error: Requested texture size [0x0] is invalid.
    at Ee (ml5.min.js:1)
    at Qe (ml5.min.js:1)
    at Ze (ml5.min.js:1)
    at e.createMatrixTexture (ml5.min.js:1)
    at e.acquireTexture (ml5.min.js:1)
    at e.uploadToGPU (ml5.min.js:1)
    at e.getTexture (ml5.min.js:1)
    at e.fromPixels (ml5.min.js:1)
    at e.fromPixels (ml5.min.js:1)
    at e.fromPixels (ml5.min.js:1)
```

A few seconds later, I tried again and it worked. I have not changed anything aside from running the official posenet example provided by tensorflow.js  in a another tab beforehand. 
<img width="1606" alt="screen shot 2018-06-05 at 15 00 57" src="https://user-images.githubusercontent.com/11244145/40978236-59a1da86-68d3-11e8-8fab-e21bd098be10.png">
<img width="1606" alt="screen shot 2018-06-05 at 15 14 18" src="https://user-images.githubusercontent.com/11244145/40978237-59bdfa5e-68d3-11e8-9ed8-4934059f8596.png">

Both screenshots are attached... 
Many thanks for your work!

**Comment by oveddan** [comment]
I always get the error.  Will work on a fix.
