### ISSUE TITLE
require model name for ImageClassifier transfer learning

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-examples#26]
This is the present code for the transfer learning example:

```javascript
classifier = new ml5.ImageClassifier(video, modelLoaded);
```
Since we are planning to eventually have an empty ImageClassifier (see https://github.com/ml5js/ml5-library/issues/121 and https://github.com/ml5js/ml5-library/issues/128) I think we should require that you explicitly reference the pre-trained model. There is no default one. This is also more clear to an end-user as to what is going on.

This might change a bit if we go with the `FeatureExtractor` idea, but for now the example should probably be:

```javascript
classifier = new ml5.ImageClassifier('MobileNet', video, modelLoaded);
```

@cvalenzuela Is this already supported or do we have to add support for the above to the library?

**Comment by cvalenzuela** [comment]
Yes, agree! We do need to add support for this. It shouldn't be much work. 

Although maybe this is better to make together with the `FeatureExtractor` class. I started working on a branch for this yesterday. I hope to pick it up this weekend and submit a PR including it.

**Comment by shiffman** [comment]
Great. I am starting to wrap my head around the idea of a `FeatureExtractor` and I think it could work really well. Since transfer learning with an image classification model a la "Teachable Machine" will likely end up one of the most common applications of this, maybe we should still allow it to happen via the `ImageClassifier` natively. But to do regression or other more custom stuff, the `FeatureExtractor` would be required?

**Comment by cvalenzuela** [comment]
Yep, I think keeping the transfer learning inside `ImageClassifier` is a good idea.
I will continue to work on creating the feature extractor class then.

**Comment by cvalenzuela** [comment]
Closed, see https://github.com/ml5js/ml5-library/pull/142
