### ISSUE TITLE
featureExtractor with base64 images

### ISSUE THREAD

**Issue by lenny76** [ml5js/ml5-examples#264]
hi
is it correct that featureExtractor does not work with images in base64 format?
I have this error

Pixels passed to tf.browser.fromPixels() can not be null

thanks

**Comment by joeyklee** [comment]
Hi @lenny76 - Correct: the featureExtractor does **not** work with base64. You will need to convert images to any one of these types:  HTMLImageElement, HTMLCanvasElement, P5 Image, HTMLVideoElement, or ImageData. 

Hope this helps! + Please close if the tip above resolves the issue. Many thanks!

**Comment by joeyklee** [comment]
Thank you! ❤️🙏
