### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to fetch ml5.min.js:108

### ISSUE THREAD

**Issue by ab-dev-github** [ml5js/ml5-examples#276]
Hello All,

I have used [Teachable machine](https://teachablemachine.withgoogle.com/) to train the PoseNet model. 

I am also trying to use the code from below URL by just changing the model files, however I always get an error as below?

Am I doing something wrong or its a bug? No change in code except model files and I am referring to below instead of local ml5.min.js. 

<script src="https://unpkg.com/ml5@0.5.0/dist/ml5.min.js" type="text/javascript"></script>

[Code from Coding Train ](https://editor.p5js.org/codingtrain/sketches/c5sDNr8eM
)
Uncaught (in promise) TypeError: Failed to fetch
    at t.<anonymous> (ml5.min.js:108)
    at x (ml5.min.js:175)
    at Generator._invoke (ml5.min.js:175)
    at Generator.t.<computed> [as next] (ml5.min.js:175)
    at i (ml5.min.js:49)
    at ml5.min.js:49
    at new Promise (<anonymous>)
    at new e (ml5.min.js:56)
    at t.<anonymous> (ml5.min.js:49)
    at t.<anonymous> (ml5.min.js:108)

I am unable to upload my model to editor.p5js.org so I cannot try if it works there.

Appreciate your help / suggestions

Thanks,
AB

**Comment by joeyklee** [comment]
Hi @ab-dev-github - thanks for your question.
As mentioned in https://github.com/ml5js/ml5-examples/issues/263, custom trained posenet models in Teachable machine are not supported in ml5.js for now.

If you would like to use a custom pose classifier in ml5, you can try to use the Neural Network class and use the inputs from poseNet to train a classification model. 

Hope this helps! Closing this issue for now. Please feel free to reopen if there are other questions. 🙏

**Comment by ab-dev-github** [comment]
Thanks for update!
