### ISSUE TITLE
"Model has not loaded yet!" error in Word2Vec example

### ISSUE THREAD

**Issue by nickbae91** [ml5js/ml5-examples#40]
Hi,

When I try pressing the first button ("is similar to..."), I get a message that says "Model has not loaded yet!", even after trying again, and waiting before trying as well. Thought I might point out.

**Comment by cvalenzuela** [comment]
Fixed in https://github.com/ml5js/ml5-website/commit/6c860e8ceda7f3c217ea487c3ac8ac9e67b5ee1f
