### ISSUE TITLE
LSTMGenerator.generate blocking DOM updates

### ISSUE THREAD

**Issue by carlcorder** [ml5js/ml5-examples#41]
I noticed in the [LSTM Text Generator ](https://ml5js.org/docs/lstm-example) example that the text above the `generate` button should change to "Generating..." but doesn't actually update until after the `lstm.generate(data, gotData)` function finishes.

In the script: https://ml5js.org/docs/assets/scripts/example-lstm.js

I was able to get the "correct behavior" by wrapping the function call in a set timeout:

```javascript
setTimeout(() => lstm.generate(data, gotData), 500)
```

I guess this gives the DOM a chance to update before the blocking call to `.generate` is made? I'm not sure if this is an issue, but wanted to bring it to your attention.

**Comment by joeyklee** [comment]
Hi @carlcorder - Please see the `ml5.charRNN` for the latest on generative text. Thanks! Closing this up now.
