### ISSUE TITLE
Word2vec demo throws an exception loading vectors

### ISSUE THREAD

**Issue by ToonTalk** [ml5js/ml5-examples#42]
I tried https://ml5js.org/docs/word2vec-example in Chrome and FireFox.

There has been a problem loading the vocab: Unexpected token < in JSON at position 0
(anonymous) @ ml5.min.js:formatted:38924
Promise.catch (async)
value @ ml5.min.js:formatted:38923
e @ ml5.min.js:formatted:38905
t.default @ ml5.min.js:formatted:39008
(anonymous) @ example-word2vec.js:2
ml5.min.js:formatted:38975 Uncaught Error: Invalid input, vector not found for: rainbow,kitten

**Comment by cvalenzuela** [comment]
Fixed in https://github.com/ml5js/ml5-website/commit/6c860e8ceda7f3c217ea487c3ac8ac9e67b5ee1f
