### ISSUE TITLE
What requires internet connection to run

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-examples#5]
We should document with the examples and in the README what will run offline and what will not.  We should be clear about when a pre-trained model is being accessed via the cloud.

**Comment by JooYoo** [comment]
Can i download the pre-trained model in local, and use ML5js total offline. So that i can implement featureExtractor() without internet.

**Comment by joeyklee** [comment]
For those following this thread, please see: 
+ https://github.com/ml5js/ml5-data-and-models-server
+ https://github.com/ml5js/ml5-library/pull/553

This is not yet in the latest ml5 release, but is now in `development` branch if you want to test out on your own build.
