### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dyqally** [ml5js/ml5-examples#52]
when I was trying to run the examples with webcam, after model loaded, this error pops up: Uncaught TypeError: Cannot read property 'length' of undefined (sketch: line 26) [copied from the web editor YOLO example]
and the PostNet example: Uncaught TypeError: ml5.PoseNet is not a constructor (sketch: line 23)
 It happens when I tried to use imagenetClassification_Video, PostNET and YOLO locally. (running on chrome)

Many thanks for the work, this is a fantastic library!

**Comment by cvalenzuela** [comment]
Can you add the code you are running? We recently updated the library, try using `https://unpkg.com/ml5@0.1.1/dist/ml5.min.js`

**Comment by dyqally** [comment]
Yes, got it working finally! thanks!!
