### ISSUE TITLE
Complete example for Pix2Pix link points to YOLO example

### ISSUE THREAD

**Issue by nsthorat** [ml5js/ml5-examples#53]
See "Here is a complete example": https://ml5js.org/docs/Pix2Pix

![image](https://user-images.githubusercontent.com/1100749/43430987-bb428150-9439-11e8-8a4f-f3b75bb82fd5.png)

**Comment by cvalenzuela** [comment]
Nice catch, will update. thanks!

**Comment by cvalenzuela** [comment]
Fixed in https://github.com/ml5js/ml5-website/commit/f84f7bd765061645f318d533557f6b645c9d6a6a
