### ISSUE TITLE
Errors in LSTM examples on the website

### ISSUE THREAD

**Issue by NHibiki** [ml5js/ml5-examples#89]
There is an error in LSTM examples on ml5js website that shows, which leads the example to crash:

```javascript
Uncaught TypeError: ml5.LSTMGenerator is not a function
```

This error is appearing in two pages:

- https://ml5js.org/docs/lstm-example
- https://ml5js.org/docs/lstm-interactive-example

It is a problem caused by mismatching of library version (LSTMGenerator -> charRNN)?

**Comment by joeyklee** [comment]
@NHibiki  - just going through and flagging this again ==> we will need to update the website to inform people that charRNN is is now class for doing LSTM. Thanks for flagging this!

**Comment by joeyklee** [comment]
Closing this issue now since we use `ml5.charRNN` now. Thanks!
