### ISSUE TITLE
Simplify PoseNet by parts example further?

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-examples#98]
Thank you @joeyklee and @mayaman for the new PoseNet API and example ❤️ 

@joeyklee I think that a `foreach()` loop and the `=>` syntax can be confusing for beginners just used to the basics of p5. Also, I worry the `drawPosition()` function (as nice as it is) might make it harder for users to be creative with the possibilities by messing around with custom drawing for different keypoints (connecting with lines, etc.) I would propose simplifying the example to something like. . .?

Let me know what you think!

```javascript
let video;
let poseNet;
let poses = [];

function setup() {
  createCanvas(640, 480);
  video = createCapture(VIDEO);
  video.size(width, height);
  poseNet = ml5.poseNet(video);
  poseNet.on('pose', function(results) {
    poses = results;
  });
  video.hide();
}

function draw() {
  image(video, 0, 0, width, height);
  strokeWeight(2);

  // For one pose only (use a for loop for multiple poses!)
  if (poses.length > 0) {
    let pose = poses[0].pose;

    // Create a pink ellipse for the nose
    fill(213, 0, 143);
    let nose = pose['nose'];
    ellipse(nose.x, nose.y, 20, 20);

    // Create a yellow ellipse for the right eye
    fill(255, 215, 0);
    let rightEye = pose['rightEye'];
    ellipse(rightEye.x, rightEye.y, 20, 20);

    // Create a yellow ellipse for the right eye
    fill(255, 215, 0);
    let leftEye = pose['leftEye'];
    ellipse(leftEye.x, leftEye.y, 20, 20);
  }
}
```

**Comment by joeyklee** [comment]
@shiffman - oh yes! This is definitely more flexible as users can then experiment with custom geometries for each feature without defining unique functions. Let's replace the current example with the one you've proposed here :)

**Comment by joeyklee** [comment]
solved by: https://github.com/ml5js/ml5-examples/pull/99
